name: Build and Package SRB2 with Official Assets

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libsdl2-dev \
            libsdl2-mixer-dev \
            libsdl2-net-dev \
            libpng-dev \
            libopenmpt-dev \
            libfluidsynth-dev \
            git \
            zlib1g-dev \
            libcurl4-openssl-dev \
            ccache \
            unzip \
            wget

      - name: Clonar código fuente de SRB2
        run: |
          git clone --depth=1 https://github.com/STJr/SRB2.git SRB2
          cd SRB2
          git submodule update --init --recursive

      - name: Configurar CMake (Release)
        run: |
          mkdir -p SRB2/build
          cd SRB2/build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DSRB2_USE_CCACHE=ON

      - name: Compilar SRB2
        run: |
          cd SRB2/build
          make -j$(nproc)

      - name: Descargar y extraer assets oficiales
        run: |
          wget https://github.com/STJr/SRB2/releases/download/SRB2_release_2.2.15/SRB2-v2215-Full.zip -O SRB2-Full.zip
          unzip SRB2-Full.zip -d srb2-assets

      - name: Preparar paquete final (ejecutable + assets)
        run: |
          mkdir package
          # Copiar ejecutable compilado
          cp SRB2/build/bin/srb2* package/
          # Copiar assets necesarios (el principal es srb2.pk3, pero puedes agregar otros si lo deseas)
          cp srb2-assets/srb2.pk3 package/
          # Opcional: copiar otros archivos de datos si los deseas (ejemplo: srb2.srb, etc.)
          ls package

      - name: Empaquetar y subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: srb2-linux-with-assets
          path: package/
