name: Build and Package SRB2 for Linux

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libsdl2-dev \
            libsdl2-mixer-dev \
            libsdl2-net-dev \
            libpng-dev \
            libopenmpt-dev \
            libfluidsynth-dev \
            git \
            zlib1g-dev \
            libcurl4-openssl-dev \
            ccache \
            unzip \
            wget

      - name: Clonar código fuente de SRB2
        run: |
          git clone --depth=1 https://github.com/STJr/SRB2.git SRB2
          cd SRB2
          git submodule update --init --recursive

      - name: Configurar CMake (Release)
        run: |
          mkdir -p SRB2/build
          cd SRB2/build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DSRB2_USE_CCACHE=ON

      - name: Compilar SRB2
        run: |
          cd SRB2/build
          make -j$(nproc)

      - name: Listar todo lo generado tras build
        run: |
          find SRB2/build

      - name: Descargar y extraer todos los assets oficiales posibles
        run: |
          wget https://github.com/STJr/SRB2/releases/download/SRB2_release_2.2.15/SRB2-v2215-Full.zip -O SRB2-Full.zip
          unzip SRB2-Full.zip -d srb2-assets
          # Listar los archivos extraídos
          ls -lh srb2-assets

      - name: Buscar binario compilado de SRB2
        id: find-bin
        run: |
          BIN_PATH=$(find SRB2/build -type f -executable -name "srb2*")
          echo "BIN_PATH=$BIN_PATH" >> $GITHUB_ENV
          echo "Binario encontrado: $BIN_PATH"

      - name: Preparar paquete final (binario + todos los assets)
        run: |
          mkdir -p package
          cp $BIN_PATH package/
          # Copiar TODOS los archivos esenciales base (pk3, dta, srb, scripts, txt, etc)
          cp srb2-assets/*.{pk3,dta,srb,sh,txt,ico,png,bat,so,dll,exe,cfg} package/ 2>/dev/null || true
          # Copiar subcarpetas relevantes (por ejemplo, savegames o scripts si existen)
          for d in music patch player zones; do
            [ -d "srb2-assets/$d" ] && cp -r "srb2-assets/$d" package/;
          done
          echo "Contenido final del paquete:"
          ls -lh package

      - name: Empaquetar y subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: srb2-linux-with-all-assets
          path: package/
