name: Compilar Fastfetch en Docker Debian

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:11

    steps:
      - name: Instalar herramientas base
        run: |
          apt update
          apt install -y git build-essential cmake pkg-config \
                         libxcb1-dev libx11-dev libdrm-dev \
                         libpci-dev libgl1-mesa-dev

      - name: Clonar fastfetch
        run: git clone --depth=1 https://github.com/fastfetch-cli/fastfetch.git

      - name: Compilar
        run: |
          cd fastfetch
          mkdir -p build
          cd build
          cmake ..
          cmake --build . --target fastfetch

      - name: Subir binario
        uses: actions/upload-artifact@v4
        with:
          name: fastfetch-debian11
          path: fastfetch/build/fastfetch
