name: Build Impression (solo espa単ol)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Instala dependencias necesarias
        run: |
          sudo apt-get update
          sudo apt-get install -y git meson ninja-build pkg-config python3-pip gettext \
            libgtk-4-dev libadwaita-1-dev libgranite-dev libarchive-dev \
            appstream util-linux desktop-file-utils blueprint-compiler

      - name: Clona el repositorio de Impression desde GitLab
        run: git clone --depth 1 https://gitlab.com/adhami3310/Impression.git

      - name: Elimina traducciones excepto espa単ol
        run: |
          find Impression/po -type f ! -name 'es.po' -name '*.po' -delete

      - name: Parchea referencias de idiomas para solo espa単ol
        run: |
          sed -i "s/'cs',//g; s/'da',//g; s/'de',//g; s/'el',//g; s/'en_GB',//g; s/'eo',//g; s/'es',//g; s/'eu',//g; s/'fr',//g; s/'hr',//g; s/'hu',//g; s/'id',//g; s/'it',//g; s/'ja',//g; s/'ko',//g; s/'nl',//g; s/'oc',//g; s/'pl',//g; s/'pt_BR',//g; s/'ru',//g; s/'sk',//g; s/'tr',//g; s/'zh_CN',//g;" Impression/po/meson.build
          sed -i "s/languages: .*/languages: ['es']/" Impression/po/meson.build

      - name: Compila Impression con Meson y Ninja (solo espa単ol)
        working-directory: Impression
        run: |
          meson setup build
          ninja -C build

      - name: Empaqueta el binario
        working-directory: Impression/build
        run: tar czvf impression-build.tar.gz *

      - name: Sube el artefacto de build
        uses: actions/upload-artifact@v4
        with:
          name: impression-build
          path: Impression/build/impression
