name: Build Impression (solo español)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Instala dependencias necesarias
        run: |
          sudo apt-get update
          sudo apt-get install -y git meson ninja-build pkg-config python3-pip gettext \
            libgtk-4-dev libadwaita-1-dev libgranite-dev libarchive-dev \
            appstream util-linux desktop-file-utils blueprint-compiler

      - name: Clona el repositorio de Impression desde GitLab
        run: git clone --depth 1 https://gitlab.com/adhami3310/Impression.git

      - name: Elimina traducciones excepto español
        run: |
          find Impression/po -type f ! -name 'es.po' -name '*.po' -delete

      - name: Compila Impression con Meson y Ninja (solo español)
        working-directory: Impression
        run: |
          meson --prefix=/usr build
          ninja -C build

      - name: Empaqueta el binario
        working-directory: Impression/build
        run: tar czvf impression-build.tar.gz *

      - name: Sube el artefacto de build
        uses: actions/upload-artifact@v4
        with:
          name: impression-build
          path: Impression/build/impression
