---
name: LogFox Release APK (Signed)
on:
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - name: Clone LogFox repo
        run: git clone --depth 1 https://github.com/F0x1d/LogFox.git
      - name: Decode keystore into app dir
        run: >
          echo "${{ secrets.RELEASE_KEYSTORE_B64 }}" | base64 -d >
          LogFox/app/nube.jks
      - name: Create release signing properties in app dir
        run: >
          echo "storeFile=nube.jks" > LogFox/app/release-signing.properties

          echo "storePassword=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" >> LogFox/app/release-signing.properties

          echo "keyAlias=${{ secrets.RELEASE_KEY_ALIAS }}" >> LogFox/app/release-signing.properties

          echo "keyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}" >> LogFox/app/release-signing.properties
      - name: Ensure Gradle Wrapper is executable
        run: chmod +x ./LogFox/gradlew
      - name: Inject signingConfigs into build.gradle.kts
        run: >
          FILE="LogFox/app/build.gradle.kts"

          if ! grep -q "signingConfigs" "$FILE"; then
            awk '
              /android[[:space:]]*{/ {
                print $0
                print ""
                print "    val keystorePropertiesFile = file(\"release-signing.properties\")"
                print "    val keystoreProperties = java.util.Properties()"
                print "    if (keystorePropertiesFile.exists()) {"
                print "        keystoreProperties.load(java.io.FileInputStream(keystorePropertiesFile))"
                print "    }"
                print "    signingConfigs {"
                print "        create(\"release\") {"
                print "            storeFile = file(keystoreProperties[\"storeFile\"] as String?)"
                print "            storePassword = keystoreProperties[\"storePassword\"] as String?"
                print "            keyAlias = keystoreProperties[\"keyAlias\"] as String?"
                print "            keyPassword = keystoreProperties[\"keyPassword\"] as String?"
                print "        }"
                print "    }"
                next
              }
              { print }
            ' "$FILE" > tmp && mv tmp "$FILE"
          fi

          if ! grep -q "signingConfig(signingConfigs.getByName(\"release\"))" "$FILE"; then
            awk '
              /buildTypes[[:space:]]*{/,/}/ {
                if ($0 ~ /release[[:space:]]*{/) {
                  print $0
                  print "            signingConfig(signingConfigs.getByName(\"release\"))"
                  next
                }
              }
              { print }
            ' "$FILE" > tmp && mv tmp "$FILE"
          fi
      - name: Build release APK
        run: |
          cd LogFox
          ./gradlew assembleRelease
      - name: List APKs
        run: find LogFox -type f -name "*.apk"
      - name: Collect APKs
        run: |
          mkdir -p apk-out
          find LogFox -type f -name "*.apk" -exec cp {} apk-out/ \;
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: logfox-release-apk
          path: apk-out/*.apk
          if-no-files-found: error
