name: Build & Sign LogFox APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      - name: Clone LogFox source
        run: |
          git clone --depth 1 https://github.com/F0x1d/LogFox.git

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Decode keystore into app dir
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE_B64 }}" | base64 -d > LogFox/app/nube.jks

      - name: Create release signing properties in app dir
        run: |
          echo "storeFile=nube.jks" > LogFox/app/release-signing.properties
          echo "storePassword=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" >> LogFox/app/release-signing.properties
          echo "keyAlias=${{ secrets.RELEASE_KEY_ALIAS }}" >> LogFox/app/release-signing.properties
          echo "keyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}" >> LogFox/app/release-signing.properties

      - name: Ensure Gradle Wrapper is executable
        run: chmod +x ./LogFox/gradlew

      - name: Conditionally inject signingConfigs if needed (Kotlin DSL)
        run: |
          set -e
          cd LogFox/app

          # Inyecta signingConfigs si no existe
          if ! grep -q 'signingConfigs' build.gradle.kts; then
            echo "No signingConfigs found, injecting..."
            awk '
              /android[[:space:]]*{/ && !x {
                print
                print "    signingConfigs {"
                print "        create(\"release\") {"
                print "            val props = java.util.Properties().apply {"
                print "                val file = rootProject.file(\"app/release-signing.properties\")"
                print "                if (file.exists()) {"
                print "                    file.inputStream().use { load(it) }"
                print "                }"
                print "            }"
                print "            storeFile = file(props[\"storeFile\"] as String)"
                print "            storePassword = props[\"storePassword\"] as String"
                print "            keyAlias = props[\"keyAlias\"] as String"
                print "            keyPassword = props[\"keyPassword\"] as String"
                print "        }"
                print "    }"
                x=1
                next
              }
              { print }
            ' build.gradle.kts > build.gradle.kts.tmp && mv build.gradle.kts.tmp build.gradle.kts
          else
            echo "signingConfigs block already present, skipping injection."
          fi

          # Inyecta la referencia en buildTypes.release si falta
          if ! grep -q 'signingConfig = signingConfigs.getByName("release")' build.gradle.kts; then
            echo "Injecting signingConfig reference in buildTypes.release..."
            awk '
              /buildTypes[[:space:]]*{/ && !x {
                print
                x=1
              }
              /getByName\(\"release\"\)[[:space:]]*{/ && !y {
                print
                print "            signingConfig = signingConfigs.getByName(\"release\")"
                y=1
                next
              }
              { print }
            ' build.gradle.kts > build.gradle.kts.tmp && mv build.gradle.kts.tmp build.gradle.kts
          else
            echo "buildTypes.release already uses signingConfig, skipping."
          fi

      - name: Build release APK (with stacktrace)
        run: cd LogFox && ./gradlew assembleRelease --stacktrace

      - name: List APKs
        run: find LogFox/app -type f -name "*.apk"

      - name: Collect APKs
        run: |
          mkdir -p apk-out
          find LogFox/app -type f -name "*.apk" -exec cp {} apk-out/ \;

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: logfox-release-apk
          path: apk-out/*.apk
          if-no-files-found: warn
