name: Build Minimal Java SDK

on:
  workflow_dispatch:

jobs:
  build-jre:
    runs-on: ubuntu-latest
    steps:
      - name: Crear directorio de trabajo
        run: mkdir minimal-jdk

      - name: Descargar JRE headless de Adoptium
        working-directory: minimal-jdk
        run: |
          wget https://github.com/adoptium/temurin17-binaries/releases/latest/download/OpenJDK17U-jre_x64_linux_hotspot_17_latest.tar.gz

      - name: Extraer JRE
        working-directory: minimal-jdk
        run: |
          tar -xzvf OpenJDK17U-jre_x64_linux_hotspot_17_latest.tar.gz

      - name: Eliminar archivos innecesarios (opcional)
        working-directory: minimal-jdk
        run: |
          JREFOLDER=$(ls -d */ | head -n 1)
          rm -rf ${JREFOLDER}/lib/missioncontrol \
                 ${JREFOLDER}/lib/visualvm \
                 ${JREFOLDER}/lib/src.zip \
                 ${JREFOLDER}/demo \
                 ${JREFOLDER}/sample \
                 ${JREFOLDER}/man \
                 ${JREFOLDER}/include

      - name: Verificar keytool
        working-directory: minimal-jdk
        run: |
          JREFOLDER=$(ls -d */ | head -n 1)
          if [ -f "${JREFOLDER}/bin/keytool" ]; then echo "keytool está presente"; else exit 1; fi

      - name: Publicar como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: minimal-jre
          path: minimal-jdk/*
