name: Build Trackma GTK AppImage

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repo (no source code here)
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3 python3-pip python3-gi python3-gi-cairo gir1.2-gtk-3.0 python3-setuptools python3-wheel python3-appdirs appstream-util desktop-file-utils wget libgirepository1.0-dev libglib2.0-dev libgtk-3-dev patchelf

      - name: Clone Trackma repo
        run: |
          git clone https://github.com/z411/trackma.git
          cd trackma
          git submodule update --init --recursive

      - name: Install Python dependencies
        run: |
          cd trackma
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install pyinstaller

      - name: Build Trackma GTK AppImage
        run: |
          cd trackma
          # Instalar dependencias para AppImage
          pip3 install appimage-builder
          # Descargar appimage-builder recipe si no está presente
          if [ ! -f AppImageBuilder.yml ]; then
            wget https://raw.githubusercontent.com/z411/trackma/master/AppImageBuilder.yml
          fi
          # Generar la AppImage
          appimage-builder --recipe AppImageBuilder.yml
          # Mover el resultado al directorio superior si existe
          APPIMAGE=$(ls *.AppImage | head -n 1)
          if [ -f "$APPIMAGE" ]; then
            mv "$APPIMAGE" ../
          fi

      - name: Upload AppImage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trackma-gtk-AppImage
          path: trackma-gtk*.AppImage
          if-no-files-found: warn

      # También subir cualquier AppImage que haya quedado en la raíz
      - name: Upload root AppImage as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: trackma-gtk-AppImage-root
          path: trackma-gtk*.AppImage
          if-no-files-found: ignore
