name: Build Tuba Tarball Portable (Arch)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build and package tarball in Arch Linux Docker
        run: |
          set -euxo pipefail
          docker run --rm -v "$PWD:/workspace" -w /workspace archlinux:latest bash -c '
            pacman -Syu --noconfirm
            pacman -S --noconfirm base-devel git meson ninja vala \
              gtk4 libadwaita libsoup3 libsecret gtksourceview5 icu \
              json-glib glib2 libxml2 gobject-introspection patchelf \
              hicolor-icon-theme desktop-file-utils libgee librsvg

            # Clonar y compilar
            git clone --depth=1 https://github.com/GeopJr/Tuba.git tuba-src
            cd tuba-src
            meson setup build
            meson compile -C build
            DESTDIR=/workspace/Tuba.AppDir meson install -C build
            cd /workspace

            # Copiar dependencias compartidas necesarias 
            mkdir -p Tuba.AppDir/usr/lib
            BIN=/workspace/Tuba.AppDir/usr/local/bin/dev.geopjr.Tuba
            ldd "$BIN" | awk '"'"'{if ($3 ~ /^\//) print $3}'"'"' | while read -r lib; do
              cp -n "$lib" /workspace/Tuba.AppDir/usr/lib/ || true
            done

            cd Tuba.AppDir
            tar czf ../tuba-portable.tar.gz .
            cd ..
          '

      - name: Subir tarball como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: tuba-tarball
          path: tuba-portable.tar.gz
