name: Build Tuba AppImage on Arch

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Build in Arch Linux Docker container
      run: |
        docker run --rm -v $PWD:/workspace -w /workspace archlinux:latest /bin/bash -c "
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git meson ninja wget patchelf \
            gtk4 libadwaita libsoup3 libsecret gtksourceview5 icu \
            json-glib glib2 libxml2 gobject-introspection make

          # Descarga linuxdeploy y el plugin gtk
          wget -c https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          wget -c https://github.com/linuxdeploy/linuxdeploy-plugin-gtk/releases/download/continuous/linuxdeploy-plugin-gtk.sh
          chmod +x linuxdeploy-plugin-gtk.sh

          # Clona Tuba y construye
          git clone --depth=1 https://github.com/GeopJr/Tuba.git tuba-src
          cd tuba-src
          meson setup build
          meson compile -C build
          DESTDIR=/workspace/AppDir meson install -C build

          # Empaqueta la AppImage
          cd /workspace
          export APPDIR=/workspace/AppDir
          ./linuxdeploy-x86_64.AppImage --appdir \$APPDIR --output appimage --plugin gtk
        "

    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: tuba-appimage
        path: ./*.AppImage
