name: Build Tuba AppImage (Arch, sin linuxdeploy)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Build and package AppImage in Arch Linux Docker
      run: |
        set -euxo pipefail

        docker run --rm -v "$PWD:/workspace" -w /workspace archlinux:latest bash -c "
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git meson ninja vala \
            gtk4 libadwaita libsoup3 libsecret gtksourceview5 icu \
            json-glib glib2 libxml2 gobject-introspection wget patchelf \
            hicolor-icon-theme desktop-file-utils

          git clone --depth=1 https://github.com/GeopJr/Tuba.git tuba-src
          cd tuba-src
          meson setup build
          meson compile -C build
          DESTDIR=/workspace/AppDir meson install -C build
          cd /workspace

          mkdir -p AppDir/usr/lib AppDir/usr/bin AppDir/usr/share
          EXEC=tuba

          ldd AppDir/usr/bin/\$EXEC | awk '{if (\$3 ~ /^\\//) print \$3}' | while read -r lib; do
            [ -f \"\$lib\" ] && cp -n \"\$lib\" AppDir/usr/lib/ || true
          done

          echo '[Desktop Entry]' > AppDir/dev.geopjr.Tuba.desktop
          echo 'Type=Application' >> AppDir/dev.geopjr.Tuba.desktop
          echo 'Name=Tuba' >> AppDir/dev.geopjr.Tuba.desktop
          echo 'Exec=tuba' >> AppDir/dev.geopjr.Tuba.desktop
          echo 'Icon=dev.geopjr.Tuba' >> AppDir/dev.geopjr.Tuba.desktop
          echo 'Categories=Network;' >> AppDir/dev.geopjr.Tuba.desktop
          echo 'Comment=Browse the Fediverse' >> AppDir/dev.geopjr.Tuba.desktop
          echo 'Terminal=false' >> AppDir/dev.geopjr.Tuba.desktop

          if [ ! -f AppDir/dev.geopjr.Tuba.svg ]; then
            echo '<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"64\" height=\"64\"><rect width=\"100%\" height=\"100%\" fill=\"#666\"/><text x=\"50%\" y=\"50%\" font-size=\"24\" text-anchor=\"middle\" fill=\"#fff\" dy=\".3em\">T</text></svg>' > AppDir/dev.geopjr.Tuba.svg
          fi

          echo '#!/bin/sh' > AppDir/AppRun
          echo 'HERE=\"\$(dirname \"\$(readlink -f \"\$0\")\")\"' >> AppDir/AppRun
          echo 'export LD_LIBRARY_PATH=\"\$HERE/usr/lib:\$LD_LIBRARY_PATH\"' >> AppDir/AppRun
          echo 'exec \"\$HERE/usr/bin/\$EXEC\" \"\$@\"' >> AppDir/AppRun
          chmod +x AppDir/AppRun

          wget -O appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool
          ./appimagetool AppDir
          mv ./*.AppImage /workspace/
        "

    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: tuba-appimage
        path: ./*.AppImage
