name: Build Tuba Tarball (Arch)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build and package tarball in Arch Linux Docker
        run: |
          set -euxo pipefail
          docker run --rm -v "$PWD:/workspace" -w /workspace archlinux:latest bash -c '
            pacman -Syu --noconfirm
            pacman -S --noconfirm base-devel git meson ninja vala \
              gtk4 libadwaita libsoup3 libsecret gtksourceview5 icu \
              json-glib glib2 libxml2 gobject-introspection patchelf \
              hicolor-icon-theme desktop-file-utils libgee librsvg

            git clone --depth=1 https://github.com/GeopJr/Tuba.git tuba-src
            cd tuba-src
            meson setup build
            meson compile -C build
            DESTDIR=/workspace/Tuba.AppDir meson install -C build
            cd /workspace

            tar czf tuba-portable.tar.gz -C Tuba.AppDir .
          '

      - name: Subir tarball como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: tuba-tarball
          path: tuba-portable.tar.gz
