name: Build Tuba Client

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          meson \
          valac \
          libjson-glib-dev \
          libxml2-dev \
          libgee-0.8-dev \
          libsoup3.0-dev \
          libadwaita-1-dev \
          libsecret-1-dev \
          libgtksourceview-5-dev \
          libicu-dev \
          git \
          make

    - name: Clone Tuba (latest release)
      run: |
        git clone --depth=1 https://github.com/GeopJr/Tuba.git tuba-src

    - name: Build Tuba
      working-directory: ./tuba-src
      run: |
        meson setup build
        meson compile -C build

    - name: Package build artifacts
      working-directory: ./tuba-src/build
      run: |
        tar czf ../../tuba-build.tar.gz .

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: tuba-build
        path: tuba-build.tar.gz
