name: Untrackme

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git wget unzip

      - name: Clone UntrackMe repo
        run: git clone --depth 1 https://framagit.org/tom79/nitterizeme.git

      - name: Ensure Gradle Wrapper
        working-directory: nitterizeme
        run: chmod +x ./gradlew

      - name: Build debug APK
        working-directory: nitterizeme
        run: ./gradlew assembleDebug

      - name: List and collect APKs
        working-directory: nitterizeme
        run: |
          echo "Buscando APK generadas..."
          find . -type f -name "*.apk"
          mkdir -p ../apk-out
          find . -type f -name "*.apk" -exec cp {} ../apk-out/ \;

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: untrackme-debug-apk
          path: apk-out/*.apk
          if-no-files-found: error
