---
name: Untrackme Release APK
on:
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git wget unzip
      - name: Clone UntrackMe repo
        run: git clone --depth 1 https://framagit.org/tom79/nitterizeme.git
      - name: Ensure Gradle Wrapper
        run: chmod +x ./nitterizeme/gradlew
      - name: Restore keystore from secret
        run: echo "${{ secrets.RELEASE_KEYSTORE_B64 }}" | base64 -d > nube.jks
      - name: Create release signing properties
        run: >
          echo "storeFile=../nube.jks" > nitterizeme/release-signing.properties

          echo "storePassword=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" >> nitterizeme/release-signing.properties

          echo "keyAlias=${{ secrets.RELEASE_KEY_ALIAS }}" >> nitterizeme/release-signing.properties

          echo "keyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}" >> nitterizeme/release-signing.properties
      - name: Build release APK
        run: cd nitterizeme && ./gradlew assembleRelease
      - name: List APKs
        run: find nitterizeme -type f -name "*.apk"
      - name: Collect APKs
        run: |
          mkdir -p apk-out
          find nitterizeme -type f -name "*.apk" -exec cp {} apk-out/ \;
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: untrackme-release-apk
          path: apk-out/*.apk
          if-no-files-found: error
