name: Untrackme Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git wget unzip

      - name: Clone UntrackMe repo
        run: git clone --depth 1 https://framagit.org/tom79/nitterizeme.git

      - name: Ensure Gradle Wrapper
        working-directory: nitterizeme
        run: chmod +x ./gradlew

      - name: Restore keystore from secret
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE_B64 }}" | base64 -d > nube.jks

      - name: Create release signing properties
        run: |
          cat << EOF > nitterizeme/release-signing.properties
          storeFile=../nube.jks
          storePassword=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.RELEASE_KEY_ALIAS }}
          keyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}
          EOF

      - name: Build release APK
        working-directory: nitterizeme
        run: ./gradlew assembleRelease

      - name: Diagnóstico: Lista todos los APK generados
        working-directory: nitterizeme
        run: find . -type f -name "*.apk"

      - name: List and collect APKs
        working-directory: nitterizeme
        run: |
          echo "Buscando APK generadas..."
          mkdir -p ../apk-out
          find . -type f -name "*.apk" -exec cp {} ../apk-out/ \;

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: untrackme-release-apk
          path: apk-out/*.apk
          if-no-files-found: error
